version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install uv
      - uv sync --no-dev --group docs

sphinx:
  configuration: doc/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
