# First just blindly copy paste what is default values from the docs page
# https://github.com/codecov/support/wiki/codecov.yml
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

# But for luigi we do not want any comments
comment: false
